### ISSUE TITLE
I want to enable `bunx(or npx, pnpm create, yarn create) create-fuwari`.

### ISSUE THREAD

**Issue by L4Ph** [saicaca/fuwari#210]
So I decided to create it. 
It will probably become a boilerplate with even higher freedom of degree once it's completed.

I'm still in the process of making it, but I'd like to complete it someday.

https://github.com/L4Ph/create-fuwari

**Comment by L4Ph** [comment]
Once it's complete and works fine, I'll transfer the repository to saicaca. (I don't know when that will be.)

**Comment by saicaca** [comment]
Thank you for your effort!

I failed to get this to work on my device. I'm unfamiliar with this, so your help might be needed to determine the problem.🥲

```bash
saica@DESKTOP-573IMD5:~$ pnpm create fuwari@latest
.local/share/pnpm/store/v3/tmp/dlx-1570  |   +2 +
.local/share/pnpm/store/v3/tmp/dlx-1570  | Progress: resolved 2, reused 2, downloaded 0, added 2, done
✔ Please enter the project name: fuwari
✔ Please enter the site title: Fuwari
✔ Please enter the site subtitle: Demo Site
✔ Please select the language of the site. en
✔ Install Dependencies? yes
Error downloading template: Tarball not found: /home/saica/.cache/giget/gh/saicaca-fuwari/main.tar.gz (offline: true)
Error: Tarball not found: /home/saica/.cache/giget/gh/saicaca-fuwari/main.tar.gz (offline: true)
    at r1 (file:///home/saica/.local/share/pnpm/store/v3/tmp/dlx-1570/node_modules/.pnpm/create-fuwari@0.0.6_typescript@5.6.3/node_modules/create-fuwari/dist/index.mjs:38:14007)
    at async n1 (file:///home/saica/.local/share/pnpm/store/v3/tmp/dlx-1570/node_modules/.pnpm/create-fuwari@0.0.6_typescript@5.6.3/node_modules/create-fuwari/dist/index.mjs:38:14722)
    at async file:///home/saica/.local/share/pnpm/store/v3/tmp/dlx-1570/node_modules/.pnpm/create-fuwari@0.0.6_typescript@5.6.3/node_modules/create-fuwari/dist/index.mjs:38:15291
node:internal/fs/promises:633
  return new FileHandle(await PromisePrototypeThen(
                        ^

Error: ENOENT: no such file or directory, open 'undefined/src/config.ts'
    at async open (node:internal/fs/promises:633:25)
    at async Object.readFile (node:internal/fs/promises:1242:14)
    at async file:///home/saica/.local/share/pnpm/store/v3/tmp/dlx-1570/node_modules/.pnpm/create-fuwari@0.0.6_typescript@5.6.3/node_modules/create-fuwari/dist/index.mjs:38:15335 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'undefined/src/config.ts'
}

Node.js v21.6.2
```

**Comment by L4Ph** [comment]
I'm investigating the same issue, but I don't know why it's happening...

It's working fine, so I think it's probably a dependency issue, but I don't know what the problem is...

https://github.com/L4Ph/create-fuwari/issues/1

**Comment by L4Ph** [comment]
@saicaca 

There was a bug related to tsup (or rather esbuild). I've switched to rslib, so please clone and run the following commands:
```sh
git clone https://github.com/L4Ph/create-fuwari.git
cd create-fuwari
pnpm i
pnpm run build
node ./bin/cli.mjs //shebang
```
and let me know the result.

**Comment by L4Ph** [comment]
https://www.npmjs.com/package/create-fuwari

**Comment by saicaca** [comment]
Sorry for the late reply, and thank you so much for your efforts!

I'll update the README later and include this as one of the installation methods. Also, please feel free to add me as a collaborator. Thanks again!
