### ISSUE TITLE
Search component missing from PROD environment

### ISSUE THREAD

**Issue by CarlosCB1986** [saicaca/fuwari#253]
The search component is not appearing in PROD environment, whereas it does appear in DEV environment.

<img width="507" alt="image" src="https://github.com/user-attachments/assets/b41bd11b-2625-430f-a84f-2fa856cc3e54">

**Comment by CarlosCB1986** [comment]
Console is throwing errors:
`(index):1 [astro-island] Error hydrating /_astro/Search.BI8uCq4K.js TypeError: Illegal invocation
    at j (render.DXsOrPE0.js:1:12078)
    at Wn (render.DXsOrPE0.js:1:12385)
    at Ue (Search.BI8uCq4K.js:1:5148)
    at render.DXsOrPE0.js:1:16795
    at st (render.DXsOrPE0.js:1:6707)
    at ie (render.DXsOrPE0.js:1:7384)
    at $ (render.DXsOrPE0.js:1:3153)
    at Ut (render.DXsOrPE0.js:1:4096)
    at render.DXsOrPE0.js:1:16735
    at st (render.DXsOrPE0.js:1:6707)
start @ (index):1
await in start
childrenConnectedCallback @ (index):1
t @ (index):1
(anonymous) @ (index):1Understand this errorAI
render.DXsOrPE0.js:1 hydration_mismatch`
